function [sign] = orient2(pa,pb,pc,pp)
%ORIENT2 return the orientation of PP wrt the face PA,PB,PC.
%
%   See also ORIENT1

%   Darren Engwirda : 2018 --
%   Email           : de2363@columbia.edu
%   Last updated    : 10/07/2018

%---------------------------------------------- calc. det(S)
    smat = zeros(+3,+3,size(pp,1));
    smat(1,:,:) = pa-pp;
    smat(2,:,:) = pb-pp;
    smat(3,:,:) = pc-pp;

    sign = ...
    smat(1,1,:) .* ( ...
	smat(2,2,:) .* smat(3,3,:) ... 
  - smat(2,3,:) .* smat(3,2,:) ...
	    ) - ... 
    smat(1,2,:) .* ( ...
	smat(2,1,:) .* smat(3,3,:) ... 
  - smat(2,3,:) .* smat(3,1,:) ...
	    ) + ...
	smat(1,3,:) .* ( ...
	smat(2,1,:) .* smat(3,2,:) ... 
  - smat(2,2,:) .* smat(3,1,:) ...
	    ) ;

end



